import './globals.css'

import React from 'react'

import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * Root layout props
 */
interface IRootLayout {
  /**
   * a component / react node
   */
  children: React.ReactNode
}

const RootLayout = (props: IRootLayout) => {
  return (
    <html lang="en">
      <body className={inter.className} data-testid="container__application">
        {props.children}
      </body>
    </html>
  )
}

export default RootLayout
