export const ENV = {
  NODE_ENV: process.env.NODE_ENV,
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  WEB_BASE_URL: process.env.NEXT_PUBLIC_WEB_BASE_URL,
  GOOGLE_ANALYTIC_MEASUREMENT_ID:
    process.env.NEXT_PUBLIC_GOOGLE_ANALYTIC_MEASUREMENT_ID,
}
